### ISSUE TITLE
Location picker's severely packed

### ISSUE THREAD

**Issue by martinrios95** [kh3dr0n/Pizza-delivery#2]
I have got a problem using this repo and replacing Google Maps' API to an EditText to write addresses.

That activity is being used from a JAR file, which means that couldn't be seen by editing on Android Studio.

I experienced some issues writing an address and passing it into LocationPickerActivity via Bundle, but it doesn't work.

Maybe, cannot you use another location's API and include the class on Java's source-code section?

**Comment by kh3dr0n** [comment]
Sorry I can't do that for now, I have a lot of work.
Try to check the documentation of the lib [Leku](https://github.com/SchibstedSpain/Leku) and search for your need.
Otherwise try use another library or code your needs just with Google Maps.

**Comment by martinrios95** [comment]
Okay, I've tried using an EditText to just write a valid address to pass it on Node.js for my local pizza store. So they just need the address... nor Google Maps or another location-pointer API.

But I'll try reading Leku's docs to have another information using that library. I thought it was yours, so I was wrong.

By the way, thanks for the answer! 😄
